import React, { useState, useEffect } from "react";
import { Parallax } from "react-parallax";
import { Link } from "react-router-dom";
import { Carousel, Container, Row, Col, Image, Button } from "react-bootstrap";
import "./Events.css"
import { EventsCardsHead } from "./objects/EventsCards";
import img2 from "../localAssets/1.png";
import test2 from "../localAssets/bgTest.png"



function Events() {

    return (
        <div fluid="true" className="frame" >

            <Container className="body-splitter-sm">  </Container>

            <Container className="contact-banner">
                <Image>

                </Image>
            </Container>         

            <Container fluid="true" className="page-holder-full">

            <Container className="body-splitter-xs"/>

            <Col className="NG-column">
                <Row className="NG-head" lg>
                    <EventsCardsHead pDate="22-OCT-2022" pTitle="Titulo" pBody="We need
                     to future-proof this win-win-win. \n\nGreat plan! Let me diarize this, and we can synchronize ourselves at a later timeframe, for strategic staircase wiggle room. \n\nIdea shower: what's our go to market strategy? Table the discussion; I just wanted to give you a heads-up, and run it up the flag pole for a performance review. \n\nIt's a simple lift and shift job. Throughput criticality, pre-think our game-plan. So if you could do that, that would be great for critical mass. \n\nPull in ten extra bodies to help roll the tortoise, a loss a day will keep you focused, then loop back. \n\nBack-end of third quarter, meeting assassins get buy-in to close the loop. When does this sun set? \n\nThe website doesn't have the theme I was going for. \nSomething summery; colorful. This looks perfect. Just Photoshop out the dog, add a baby, and make the curtains blue. We also need to add this 2000 line essay. Can the black be darker? Can you make it stand out more? I know you've made thirty iterations, but can we go back to the first one? That was the best version I remember. I'll know it when I see it; that’s not what I saw in my head at all. Can you put find us on facebook by the facebook logo?
                     to future-proof this win-win-win. \n\nGreat plan! Let me diarize this, and we can synchronize ourselves at a later timeframe, for strategic staircase wiggle room. \n\nIdea shower: what's our go to market strategy? Table the discussion; I just wanted to give you a heads-up, and run it up the flag pole for a performance review. \n\nIt's a simple lift and shift job. Throughput criticality, pre-think our game-plan. So if you could do that, that would be great for critical mass. \n\nPull in ten extra bodies to help roll the tortoise, a loss a day will keep you focused, then loop back. \n\nBack-end of third quarter, meeting assassins get buy-in to close the loop. When does this sun set? \n\nThe website doesn't have the theme I was going for. \nSomething summery; colorful. This looks perfect. Just Photoshop out the dog, add a baby, and make the curtains blue. We also need to add this 2000 line essay. Can the black be darker? Can you make it stand out more? I know you've made thirty iterations, but can we go back to the first one? That was the best version I remember. I'll know it when I see it; that’s not what I saw in my head at all. Can you put find us on facebook by the facebook logo?
                     to future-proof this win-win-win. \n\nGreat plan! Let me diarize this, and we can synchronize ourselves at a later timeframe, for strategic staircase wiggle room. \n\nIdea shower: what's our go to market strategy? Table the discussion; I just wanted to give you a heads-up, and run it up the flag pole for a performance review. \n\nIt's a simple lift and shift job. Throughput criticality, pre-think our game-plan. So if you could do that, that would be great for critical mass. \n\nPull in ten extra bodies to help roll the tortoise, a loss a day will keep you focused, then loop back. \n\nBack-end of third quarter, meeting assassins get buy-in to close the loop. When does this sun set? \n\nThe website doesn't have the theme I was going for. \nSomething summery; colorful. This looks perfect. Just Photoshop out the dog, add a baby, and make the curtains blue. We also need to add this 2000 line essay. Can the black be darker? Can you make it stand out more? I know you've made thirty iterations, but can we go back to the first one? That was the best version I remember. I'll know it when I see it; that’s not what I saw in my head at all. Can you put find us on facebook by the facebook logo?
                     to future-proof this win-win-win. \n\nGreat plan! Let me diarize this, and we can synchronize ourselves at a later timeframe, for strategic staircase wiggle room. \n\nIdea shower: what's our go to market strategy? Table the discussion; I just wanted to give you a heads-up, and run it up the flag pole for a performance review. \n\nIt's a simple lift and shift job. Throughput criticality, pre-think our game-plan. So if you could do that, that would be great for critical mass. \n\nPull in ten extra bodies to help roll the tortoise, a loss a day will keep you focused, then loop back. \n\nBack-end of third quarter, meeting assassins get buy-in to close the loop. When does this sun set? \n\nThe website doesn't have the theme I was going for. \nSomething summery; colorful. This looks perfect. Just Photoshop out the dog, add a baby, and make the curtains blue. We also need to add this 2000 line essay. Can the black be darker? Can you make it stand out more? I know you've made thirty iterations, but can we go back to the first one? That was the best version I remember. I'll know it when I see it; that’s not what I saw in my head at all. Can you put find us on facebook by the facebook logo?
                     to future-proof this win-win-win. \n\nGreat plan! Let me diarize this, and we can synchronize ourselves at a later timeframe, for strategic staircase wiggle room. \n\nIdea shower: what's our go to market strategy? Table the discussion; I just wanted to give you a heads-up, and run it up the flag pole for a performance review. \n\nIt's a simple lift and shift job. Throughput criticality, pre-think our game-plan. So if you could do that, that would be great for critical mass. \n\nPull in ten extra bodies to help roll the tortoise, a loss a day will keep you focused, then loop back. \n\nBack-end of third quarter, meeting assassins get buy-in to close the loop. When does this sun set? \n\nThe website doesn't have the theme I was going for. \nSomething summery; colorful. This looks perfect. Just Photoshop out the dog, add a baby, and make the curtains blue. We also need to add this 2000 line essay. Can the black be darker? Can you make it stand out more? I know you've made thirty iterations, but can we go back to the first one? That was the best version I remember. I'll know it when I see it; that’s not what I saw in my head at all. Can you put find us on facebook by the facebook logo?
                     to future-proof this win-win-win. \n\nGreat plan! Let me diarize this, and we can synchronize ourselves at a later timeframe, for strategic staircase wiggle room. \n\nIdea shower: what's our go to market strategy? Table the discussion; I just wanted to give you a heads-up, and run it up the flag pole for a performance review. \n\nIt's a simple lift and shift job. Throughput criticality, pre-think our game-plan. So if you could do that, that would be great for critical mass. \n\nPull in ten extra bodies to help roll the tortoise, a loss a day will keep you focused, then loop back. \n\nBack-end of third quarter, meeting assassins get buy-in to close the loop. When does this sun set? \n\nThe website doesn't have the theme I was going for. \nSomething summery; colorful. This looks perfect. Just Photoshop out the dog, add a baby, and make the curtains blue. We also need to add this 2000 line essay. Can the black be darker? Can you make it stand out more? I know you've made thirty iterations, but can we go back to the first one? That was the best version I remember. I'll know it when I see it; that’s not what I saw in my head at all. Can you put find us on facebook by the facebook logo?
                     to future-proof this win-win-win. \n\nGreat plan! Let me diarize this, and we can synchronize ourselves at a later timeframe, for strategic staircase wiggle room. \n\nIdea shower: what's our go to market strategy? Table the discussion; I just wanted to give you a heads-up, and run it up the flag pole for a performance review. \n\nIt's a simple lift and shift job. Throughput criticality, pre-think our game-plan. So if you could do that, that would be great for critical mass. \n\nPull in ten extra bodies to help roll the tortoise, a loss a day will keep you focused, then loop back. \n\nBack-end of third quarter, meeting assassins get buy-in to close the loop. When does this sun set? \n\nThe website doesn't have the theme I was going for. \nSomething summery; colorful. This looks perfect. Just Photoshop out the dog, add a baby, and make the curtains blue. We also need to add this 2000 line essay. Can the black be darker? Can you make it stand out more? I know you've made thirty iterations, but can we go back to the first one? That was the best version I remember. I'll know it when I see it; that’s not what I saw in my head at all. Can you put find us on facebook by the facebook logo?" pImgURL={test2} />
                </Row>
            </Col>

            <Container className="body-splitter-xs" />


            <Col className="NG-column">
                <Row className="NG-head" lg>
                    <EventsCardsHead pDate="22-OCT-2022" pTitle="Titulo" pBody="We need to future-proof this win-win-win. \n\nGreat plan! Let me diarize this, and we can synchronize ourselves at a later timeframe, for strategic staircase wiggle room. \n\nIdea shower: what's our go to market strategy? Table the discussion; I just wanted to give you a heads-up, and run it up the flag pole for a performance review. \n\nIt's a simple lift and shift job. Throughput criticality, pre-think our game-plan. So if you could do that, that would be great for critical mass. \n\nPull in ten extra bodies to help roll the tortoise, a loss a day will keep you focused, then loop back. \n\nBack-end of third quarter, meeting assassins get buy-in to close the loop. When does this sun set? \n\nThe website doesn't have the theme I was going for. \nSomething summery; colorful. This looks perfect. Just Photoshop out the dog, add a baby, and make the curtains blue. We also need to add this 2000 line essay. Can the black be darker? Can you make it stand out more? I know you've made thirty iterations, but can we go back to the first one? That was the best version I remember. I'll know it when I see it; that’s not what I saw in my head at all. Can you put find us on facebook by the facebook logo?" pImgURL={img2} />                </Row>
            </Col>

            </Container>
        </div>
    );
}

export default Events;